### ISSUE TITLE
Errores de sintaxis y semanticos en archivo jobshop.java

### ISSUE THREAD

**Issue by gavendanoc** [marobayos/Simlib-Java#2]
Las variables route, meanService, probDistribJobType no tienen asignados un espacio de memoria antes de usarse.

En la linea 61.for (int j = 1; j <= numStations; ++j) se recorre la variable "stations" desde 1 hasta numStation. pero el tamaño del arreglo stations es de numStation por lo que produce in index out of bounds exception.

**Comment by marobayos** [comment]
Gracias! 
Se arregló en a6356db
